package Model;

/**
 * Represents a hint generated by the Smart Assistant.
 * 
 * @author Team Rhino
 * @version 1.0
 */
public class Hint {
    private final int row;
    private final int col;
    private final boolean isMine;
    private final String message;

    public Hint(int row, int col, boolean isMine, String message) {
        this.row = row;
        this.col = col;
        this.isMine = isMine;
        this.message = message;
    }

    public int getRow() {
        return row;
    }

    public int getCol() {
        return col;
    }

    public boolean isMine() {
        return isMine;
    }

    public String getMessage() {
        return message;
    }

    public boolean isSafe() {
        return !isMine;
    }
}
